spring.application.name=QuanLyNhaKhoa

spring.datasource.url=jdbc:mysql://ql-nhakhoa-ducvuong91.b.aivencloud.com:24573/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_CTuE0KnALSm_orq5Oad
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Giữ dữ liệu khi restart server
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false

server.forward-headers-strategy=framework